POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpdXNlcm5hbWUiLCJpZCI6IjVkNTA0NmNhYzc3NWUzMTBhNDFhMTZkYSIsImlhdCI6MTU2NTU0MzgyOH0.LfWLGN7g-eyagQarE5eDuL9Pi_MtiX7WRkJK2nk87J8

{
  "author": "Token author",
  "title": "Token title",
  "url": "www.tokeninsivut.com",
  "likes": 5
}